/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/frame/scene.gltf -o frame.jsx
Author: Dylan Dreyer Varsics (https://sketchfab.com/d.varsics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-architecture-photo-frame-33bedcb0e2064a3a97c19658e254af74
Title: 3D Architecture | Photo frame
*/

import { useEffect, useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { SRGBColorSpace } from 'three'

const HEADSHOT = '/assets/headshot.webp'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/frame/scene.gltf')
  const headshot = useTexture(HEADSHOT)

  useEffect(() => {
    headshot.colorSpace = SRGBColorSpace
    headshot.flipY = false
    headshot.needsUpdate = true
  }, [headshot])

  const photoMaterial = useMemo(() => {
    const material = materials.Material_350.clone()
    material.map = headshot
    material.color.set('#ffffff')
    material.metalness = 0
    material.roughness = 0.82
    material.needsUpdate = true
    return material
  }, [headshot, materials.Material_350])

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.011}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes['Box046_Material_#25_0'].geometry} material={materials.Material_25} />
            <mesh geometry={nodes['Box046_Material_#350_0'].geometry} material={photoMaterial} />
            <mesh geometry={nodes.Box046_Frame_0.geometry} material={materials.Frame} />
            <mesh geometry={nodes['Box046_Material_#26_0'].geometry} material={materials.Material_26} />
          </group>
        </group>
      </group>
    </group>
  )
}
