/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\assets\monitor\scene.gltf 
Author: portgl16 (https://sketchfab.com/portgl16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monitor-9f6f9018f14a4dbea1ad1aea0ce89e7c
Title: Monitor
*/

import { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/monitor/scene.gltf')

  // Screen is covered by the live Html portfolio — keep a flat dark panel, never a photo texture.
  useEffect(() => {
    const screen = materials.RenderMonitor
    if (!screen) return undefined
    screen.map = null
    screen.color.set('#020617')
    screen.roughness = 0.45
    screen.metalness = 0
    screen.needsUpdate = true
    return undefined
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <group position={[-1575.703, 30, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Cube_Case_0.geometry} material={materials.Case} />
        <mesh geometry={nodes.Cube_RenderMonitor_0.geometry} material={materials.RenderMonitor} />
        <mesh geometry={nodes.Cube_USB_0.geometry} material={materials.material} />
      </group>
      <mesh geometry={nodes.Button_Button_Material_0.geometry} material={materials.Button_Material} position={[-695.83, -497.371, 28.549]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Button_two_ButtonTwoMaterial_0.geometry} material={materials.ButtonTwoMaterial} position={[-740.479, -496.832, 27.902]} rotation={[-Math.PI / 2, 0, 0]} scale={[20, 10, 8]} />
      <mesh geometry={nodes.Button_two001_ButtonTwoMaterial001_0.geometry} material={materials['ButtonTwoMaterial.001']} position={[-792.221, -496.832, 27.902]} rotation={[-Math.PI / 2, 0, 0]} scale={[20, 10, 8]} />
    </group>
  )
}
