/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/polaroid/scene.gltf -o src/models/Polaroid.jsx
Author: Edoardo Galati (https://sketchfab.com/edoardogalati)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/polaroid-photo-sample-fe1d05e189dc4da197f6ba2717abe182
Title: Polaroid Photo Sample
*/

import { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

const PATH = '/assets/polaroid/scene.gltf'

// Author mesh is tilted in the GLTF. This rotation maps the photo face to +Y
// (desk-up); the offset then centers XZ and grounds minY at 0.
// Native footprint after this: ~32.5 × 1.44 × 32.4
const LAY_FLAT_QUAT = [-0.105301, 0, -0.290564, 0.951044]
const GROUND_OFFSET = [-10.7931, -13.6185, 3.0987]

export function Model(props) {
  const { nodes, materials } = useGLTF(PATH)

  // Frameblinn2SG ships with roughness 0 — keep the gloss so Environment can catch highlights.
  useEffect(() => {
    const glossy = materials.Frameblinn2SG
    if (!glossy) return undefined
    glossy.roughness = 0
    glossy.metalness = 0
    glossy.envMapIntensity = 1.35
    glossy.needsUpdate = true
    return undefined
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <group quaternion={LAY_FLAT_QUAT}>
        <group position={GROUND_OFFSET}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-12.943, -16.326, 9.466]}>
              <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.Frameblinn2SG} />
              <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Framelambert79SG} />
              <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.initialShadingGroup} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
